### ISSUE TITLE
URL parsing bug

### ISSUE THREAD

**Issue by bg-nikita** [Abdera7mane/Godot-SimpleHTTPClient#2]
There is the following problem in function `parse_url()` in file `URL.gd`: sometimes the script reads the port incorrectly, capturing numbers from endpoint arguments. As a result, the port may contain a few extra numbers, causing the connection to fail.

This is due to incorrect use of the `substr()` method on line 35: the second argument should look like `path_delimiter - port_delimiter`, because this argument is the **length**, not the index of the last character in the substring.

**Comment by Abdera7mane** [comment]
I apology for the delay, this was an oversight from my part, thank you for pointing that out. As such, I rewrote each call to `substr` to make it clear that a sub-string length is being passed as a second argument. I also accounted for URLs with an empty endpoint that don't end with a forward slash.
